[package]
name = "apples"
version = "0.1.0"
edition = "2021"
description = "Omtenta"
readme = "README.md"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorize = "0.1.0"
rand = "0.8.4"
